#!/bin/bash
#
source help/helpFunctions.sh
source code/bucket_create_node.sh
source code/bucket_create_client.sh
source code/bucket_create_dtr.sh
source code/bucket_create_k8s.sh
source code/bucket_ns.sh
source code/bucket_rope.sh
source code/bucket_k8sUI.sh
source code/bucket_setup.sh
source code/gen-helper-function.sh
source code/bucket_gluster.sh
source code/bucket_nfs.sh
source code/bucket_mysql.sh
source code/bucket_list.sh
source code/bucket_app.sh
source code/bucket_exec.sh
source code/bucket_show.sh
#source show/show-func.sh
#
nodename="default"
bucket="default"
nodecount=1
os="centos"
osv="7"
namespace="default"
profile="mini"
mip="default"
withbdc=0
k8sVersion="1.14.2"
nMaster=1
nWorker=1
cni="flannel"
csi="local"
dtr="shared"
noClient=0
withClient=0
withVolume=0
volumeGB=1
hook="22"
ropeType="ssh"
ropename="default"
snapname=
no_expiry=
stateful=
finit=0;
fprofile=0;
ftemplate=0;
fsall=0;
fclient=0;
fnode=0;
fmysql=0;
fmssql=0;
fdtr=0;
fk8s=0;
ftall=0;
fglust=0;
isBash=0;
glusterNode=1;
codePath="default";
file="default";
source="default";
destination="default";
execType="s";
onClient=0;
mode="create";
dbtype="standalone";
deplType="node";
clusterType="standalone";
sqlEdition="Developer"
saCred="Bucket1@sql"
ha=0;
replica=0;
sqlNode=1;
dataNode=2;
cmd1=
cmd2=
cmd3=
cmd4=
while [ "$1" != "" ]; do
    case $1 in
        -v | --version )    show_version
                            exit
                            ;;
        -h | --help )   help_bucket
                        exit
                        ;;
        snapshot )  shift
                    cmd1=$1
                    case $cmd1 in
                        -v | --version )    show_version
                                            exit
                                            ;;
                        -h | --help )       show_help_snapshot
                                            exit
                                            ;;
                        create )    shift        
                                    cmd2=$1
                                    case $cmd2 in
                                        -v | --version )    show_version
                                                            exit
                                                            ;;
                                        -h | --help )       show_help_snapshot_create
                                                            exit
                                                            ;;
                                        * )                 namespace=$1
                                                            shift
                                                            snapname=$1
                                                            shift
                                                            cmd3=$1
                                                            case $cmd3 in
                                                                --no-expiry ) no_expiry=1
                                                                              ;;
                                                                --stateful ) stateful=1
                                                                              ;;
                                                                * )           show_help_snapshot
                                                                              exit 1
                                                            esac
                                                            shift
                                                            cmd4=$1
                                                            case $cmd4 in
                                                                --no-expiry ) no_expiry=1
                                                                              ;;
                                                                --stateful ) stateful=1
                                                                              ;;
                                                                * )           show_help_snapshot
                                                                              exit 1
                                                            esac
                                                            snapshot_create $namespace $snapname $no_expiry stateful
                                                            ;;
                                    esac
                                    shift
                                    ;;
                        delete )    shift        
                                    cmd2=$1
                                    case $cmd2 in
                                        -v | --version )    show_version
                                                            exit
                                                            ;;
                                        -h | --help )       show_help_snapshot_delete
                                                            exit
                                                            ;;
                                        * )                 namespace=$1
                                                            shift
                                                            snapname=$1
                                                            snapshot_delete $namespace $snapname
                                                            ;;
                                    esac
                                    shift
                                    ;;
                        restore )   shift        
                                    cmd2=$1
                                    case $cmd2 in
                                        -v | --version )    show_version
                                                            exit
                                                            ;;
                                        -h | --help )       show_help_snapshot_restore
                                                            exit
                                                            ;;
                                        * )                 namespace=$1
                                                            shift
                                                            snapname=$1
                                                            snapshot_restore $namespace $snapname
                                                            ;;
                                    esac
                                    shift
                                    ;;
                        list )      shift        
                                    cmd2=$1
                                    case $cmd2 in
                                        -v | --version )    show_version
                                                            exit
                                                            ;;
                                        -h | --help )       show_help_snapshot_list
                                                            exit
                                                            ;;
                                        * )                 namespace=$1
                                                            snapshot_list $namespace
                                                            ;;
                                    esac
                                    shift
                                    ;;
                        * )         show_help_snapshot
                                    exit 1
                    esac
                    shift
                    ;;
        create )    shift
                    cmd1=$1
                    case $cmd1 in
                        -h | --help )       help_bucket_create
                                            exit
                                            ;;
                        ns )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_create_ns
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                --name )  shift  
                                                    namespace=$1
                                                    ;;
                                                * ) help_bucket_create_ns
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_ns $namespace 
                        ;;
                        node )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_node
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -c | --count )  shift  
                                                    nodecount=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                --os )  shift  
                                                    os=$1
                                                    ;;
                                                -v | --osv )  shift  
                                                    osv=$1
                                                    ;;
                                                --withClient )  withClient=1
                                                    ;;
                                                --withVolume )  withVolume=1
                                                    ;;
                                                --volumeGB )    shift  
                                                                volumeGB=$1
                                                    ;;
                                                * ) help_bucket_create_node
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_node $namespace $nodecount $profile $os $osv $withClient $withVolume $volumeGB
                        ;;
                        mysql )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_mysql
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -t | --type )  shift  
                                                    dbtype=$1
                                                    ;;
                                                -sn | --sqlNode )  shift  
                                                    sqlNode=$1
                                                    ;;
                                                -dn | --dataNode )  shift  
                                                    dataNode=$1
                                                    ;;
                                                --withClient )  withClient=1
                                                    ;;
                                                * ) help_bucket_create_mysql
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_mysql $namespace $profile $dbtype $sqlNode $dataNode $withClient
                        ;;
                        client )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -v | --version )    show_version
                                            exit
                                            ;;
                                    -h | --help )       help_bucket_create_client
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                --name )  shift  
                                                    nodename=$1
                                                    ;;
                                                * ) help_bucket_create_client
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_client $namespace $nodename
                        ;;
                        dtr )    shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_dtr
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                --name )    shift
                                                    nodename=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                * ) help_bucket_create_dtr
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_dtr $namespace $nodename $profile
                        ;;
                        k8s )    shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_k8s
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -v | --k8sVersion ) shift
                                                    k8sVersion=$1
                                                    ;;
                                                -m | --master )    shift
                                                    nMaster=$1
                                                    ;;
                                                -w | --worker )    shift
                                                    nWorker=$1
                                                    ;;
                                                --cni )    shift
                                                    cni=$1
                                                    ;;
                                                --csi )    shift
                                                    csi=$1
                                                    ;;
                                                --dtr )    shift
                                                    dtr=$1
                                                    ;;
                                                --noClient )   noClient=1
                                                    ;;
                                                * ) help_bucket_create_k8s
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_k8s $namespace $profile $k8sVersion $nMaster $nWorker $cni $csi $dtr $noClient
                        ;;
                        k8sUI )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_create_k8sui
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                * ) help_bucket_create_k8sui
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_k8sui $namespace $k8sVersion
                        ;;
                        nfs )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_create_nfs
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                        namespace=$1
                                                        ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                * ) help_bucket_create_ns
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_nfs $namespace $profile
                        ;;
                        bdc )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_bdc
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                --name )  shift  
                                                    nodename=$1
                                                    ;;
                                                * ) help_bucket_create_bdc
                                                    exit 1
                                                    ;;
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_client $namespace $nodename
                        ;;
                        rope )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_rope
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -b | --bucket )  shift  
                                                    bucket=$1
                                                    ;;
                                                -r | --rope )  shift  
                                                    ropeType=$1
                                                    ;;
                                                -k | --hook )  shift  
                                                    hook=$1
                                                    ;;
                                                * ) help_bucket_create_rope
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_rope $bucket $ropeType $hook
                        ;;
                        gluster )    shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_gluster
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -gn | --glusterNode )   shift
                                                                        glusterNode=$1
                                                                        ;;
                                                --volumeGB )    shift
                                                                volumeGB=$1
                                                                ;;
                                                --noClient )    noClient=1
                                                                ;;
                                                * ) help_bucket_create_gluster
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_gluster $namespace $profile $glusterNode $volumeGB $noClient
                        ;;
                        * ) help_bucket_create
                            exit 1
                    esac
                shift
                ;;
        cluster )    shift
                    cmd1=$1
                    case $cmd1 in
                        -h | --help )       help_bucket_create
                                            exit
                                            ;;
                        k8s )    shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_k8s
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -v | --k8sVersion ) shift
                                                    k8sVersion=$1
                                                    ;;
                                                -m | --master )    shift
                                                    nMaster=$1
                                                    ;;
                                                -w | --worker )    shift
                                                    nWorker=$1
                                                    ;;
                                                --cni )    shift
                                                    cni=$1
                                                    ;;
                                                --csi )    shift
                                                    csi=$1
                                                    ;;
                                                --dtr )    shift
                                                    dtr=$1
                                                    ;;
                                                --noClient )   noClient=1
                                                    ;;
                                                * ) help_bucket_create_k8s
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_k8s $namespace $profile $k8sVersion $nMaster $nWorker $cni $csi $dtr $noClient
                        ;;
                        bdc )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_bdc
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                --name )  shift  
                                                    nodename=$1
                                                    ;;
                                                * ) help_bucket_create_bdc
                                                    exit 1
                                                    ;;
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_client $namespace $nodename
                        ;;
                        gluster )    shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_create_gluster
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -gn | --glusterNode )   shift
                                                                        glusterNode=$1
                                                                        ;;
                                                --volumeGB )    shift
                                                                volumeGB=$1
                                                                ;;
                                                --noClient )    noClient=1
                                                                ;;
                                                * ) help_bucket_create_gluster
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_create_gluster $namespace $profile $glusterNode $volumeGB $noClient
                        ;;
                        * ) help_bucket_create
                            exit 1
                    esac
                shift
                ;;
        app )    shift
                    cmd1=$1
                    case $cmd1 in
                        -h | --help )       help_bucket_app
                                            exit
                                            ;;
                        mysql ) shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_app_mysql
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -dt | --deplType )  shift  
                                                    deplType=$1
                                                    ;;
                                                --ha )  ha=1
                                                    ;;
                                                -c | --cred )  shift  
                                                    saCred=$1
                                                    ;;
                                                -sn | --sqlNode )  shift  
                                                    sqlNode=$1
                                                    ;;
                                                -dn | --dataNode )  shift  
                                                    dataNode=$1
                                                    ;;
                                                --withClient )  withClient=1
                                                    ;;
                                                * ) help_bucket_app_mysql
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_app_mysql $namespace $profile $deplType $ha $saCred $sqlNode $dataNode $withClient
                        ;;
                        mssql )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_app_mssql
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -p | --profile )    shift
                                                    profile=$1
                                                    ;;
                                                -dt | --deplType )  shift  
                                                    deplType=$1
                                                    ;;
                                                -e | edition ) shift
                                                    sqlEdition=$1
                                                    ;;
                                                -c | --saCred )  shift  
                                                    saCred=$1
                                                    ;;
                                                --ha )  ha=1;
                                                    ;;
                                                -r | --replica )  shift  
                                                    replica=$1
                                                    ;;
                                                --withClient )  withClient=1
                                                    ;;
                                                * ) help_bucket_app_mssql
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_app_mssql $namespace $profile $deplType $sqlEdition $saCred $ha $replica $withClient
                        ;;
                        * ) help_bucket_app
                            exit 1
                    esac
                shift
                ;;            
        show )    shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )       help_bucket_show
                                        exit
                                        ;;
                    k8s )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_show_k8s
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            * ) help_bucket_show_k8s
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_show_k8s $namespace 
                        ;;
                    k8sUI )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_show_k8sui
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                * ) help_bucket_show_k8sui
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_show_k8sui $namespace
                        ;;
                    ns )    shift
                            namespace=$1
                        shift
                        bucket_show_ns $namespace
                        ;;
                    rope )  shift
                            bucket=$1
                        shift
                        bucket_show_rope $profile
                        ;;
                    profile )   shift
                                profile=$1
                        shift
                        bucket_show_profile $profile
                        ;;
                    * ) help_bucket_show
                        exit 1
                esac
            shift
            ;;
        rm | delete )    shift
            cmd1=$1
                case $cmd1 in
                    -h | --help )       help_bucket_delete
                                        exit
                                        ;;
                    ns )    shift
                            namespace=$1
                        bucket_delete_ns $namespace 
                        ;;
                    k8s )   shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_delete_ns
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            --name )    shift  
                                                        nodename=$1
                                                        ;;
                                            * ) help_bucket_delete_k8s
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                            shift
                            bucket_delete_k8s $namespace $nodename
                        ;;
                    k8sUI )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_delete_k8sui
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                -v | --k8sVersion ) shift
                                                    k8sVersion=$1
                                                    ;;
                                                * ) help_bucket_delete_k8sui
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_delete_k8sui $namespace $k8sVersion
                        ;;
                    rope )   shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_delete_rope
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -b | --bucket )  shift  
                                                    bucket=$1
                                                    ;;
                                            -r | --rope )    shift  
                                                        ropename=$1
                                                        ;;
                                            * ) help_bucket_delete_rope
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                            shift
                            bucket_delete_rope $bucket $ropename
                        ;;
                    profile )   shift
                                profile=$1
                            bucket_delete_profile $profile 
                        ;;
                    gfs | gluster )   shift
                                      namespace=$1
                            bucket_delete_gluster $namespace 
                        ;;
                    node )  shift
                            namespace=$1
                            bucket_delete_node $namespace 
                        ;;
                    * ) help_bucket_delete
                        exit 1
                esac
                shift
            ;;
        setup )    shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )   help_bucket_setup
                                    exit
                                    ;;
                    init )      finit=1; 
                                ;;
                    profile )   fprofile=1; 
                                ;;
                    template )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )       help_bucket_setup_template
                                                        exit 1;
                                                        ;;
                                    --client )     fclient=1;
                                                        ;;
                                    --node )       fnode=1;
                                                        ;;
                                    --mysql )      fmysql=1;
                                                        ;;
                                    --mssql )      fmssql=1;
                                                        ;;
                                    --k8s )        fk8s=1;
                                                        ;;
                                    --gluster )    fglust=1;
                                                        ;;
                                    --dtr )        fdtr=1;
                                                        ;;
                                    --all )        ftall=1;
                                                        ;;      
                                    * )     help_bucket_setup_template
                                            exit 1;
                                            ;;
                                esac
                            shift
                        bucket_setup_template $fclient $fnode $fmysql $fmssql $fk8s $fglust $fdtr $ftall
                        exit 0;
                        ;;
                    all )   fsall=1; 
                            ;;
                    * ) help_bucket_setup
                        exit 1
                esac
                shift
            bucket_setup $finit $fprofile $ftemplate $fsall
            ;;
        ls | list )    shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )       help_bucket_list
                                        exit
                                        ;;
                    ns )  bucket_list_ns 
                        ;;
                    k8s )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_show_k8s
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            * ) help_bucket_show_k8s
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_show_k8s $namespace 
                        ;;
                    k8sUI )  shift
                                cmd2=$1
                                case $cmd2 in
                                    -h | --help )   help_bucket_show_k8sui
                                            exit
                                            ;;
                                    * ) while [ "$1" != "" ]; do
                                            case $1 in
                                                -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                                * ) help_bucket_show_k8sui
                                                    exit 1
                                            esac
                                            shift
                                        done
                                    ;;
                                esac
                            shift
                            bucket_show_k8sui $namespace
                        ;;
                    rope )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_list_rope
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -b | --bucket )  shift  
                                                    bucket=$1
                                                    ;;
                                            * ) help_bucket_list_rope
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_list_rope $bucket 
                        ;;
                    node )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )   help_bucket_list_node
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            * ) help_bucket_list_node
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_list_node $namespace 
                        ;;
                    profile )  bucket_show_profile
                        ;;
                    * ) help_bucket_list
                        exit 1
                esac
            shift
            ;;
        exec )    shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )   help_bucket_exec
                                    exit
                                    ;;
                    bash )  shift
                            isBash=1; 
                            nodename=$1 
                            bucket_exec_bash $nodename
                            ;;
                    code )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )       help_bucket_exec_code
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            -c | --code ) shift
                                                    codePath=$1
                                                    ;;
                                            -et |--execType )  shift  
                                                    execType=$1
                                                    ;;
                                            --onClient )  onClient=1
                                                    ;;
                                            * ) help_bucket_exec_code
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_exec_code $namespace $codePath $execType $onClient 
                        ;;
                    * ) help_bucket_exec
                        exit 1
                esac
            shift
            ;;
        push )  shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )   help_bucket_push
                                    exit
                                    ;;
                    config )    shift
                                isBash=1; 
                                nodename=$1 
                                bucket_push_config $nodename
                                ;;
                    file )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )       help_bucket_push_file
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -f | --file ) shift
                                                    file=$1
                                                    ;;
                                            -n | --namespace )  shift  
                                                    namespace=$1
                                                    ;;
                                            -b | --bucket )  shift  
                                                    bucket=$1
                                                    ;;  
                                            -et |--execType )  shift  
                                                    execType=$1
                                                    ;;
                                            * ) help_bucket_push_file
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_push_file $file $namespace $bucket $execType
                        ;;
                    * ) help_bucket_push
                        exit 1
                esac
            shift
            ;;
        pull )  shift
                cmd1=$1
                case $cmd1 in
                    -h | --help )   help_bucket_pull
                                    exit
                                    ;;
                    config )    shift
                                isBash=1; 
                                nodename=$1 
                                bucket_pull_config $nodename
                                ;;
                    file )  shift
                            cmd2=$1
                            case $cmd2 in
                                -h | --help )       help_bucket_pull_file
                                        exit
                                        ;;
                                * ) while [ "$1" != "" ]; do
                                        case $1 in
                                            -s | --source )  shift  
                                                    source=$1
                                                    ;; 
                                            -d | --destination ) shift
                                                    destination=$1
                                                    ;;
                                            * ) help_bucket_pull_file
                                                exit 1
                                        esac
                                        shift
                                    done
                                ;;
                            esac
                        shift
                        bucket_pull_file $file $source $destination
                        ;;
                    * ) help_bucket_push
                        exit 1
                esac
            shift
            ;;        
        * )         help_bucket
                    exit 1
    esac
    shift
done